server {
    set $keycloak_server KEYCLOAK_SERVER_IP;  # замените на IP-адрес сервера Keycloak
    set $keycloak_port 8080;

    server_name keycloak.yourdomain;  # замените на ваш домен для Keycloak

    error_log /var/log/nginx/keycloak.yourdomain.error.log;
    access_log /var/log/nginx/keycloak.yourdomain.access.log;

    # rewrite ^/auth/(.*) /$1 permanent;
    location / {
        proxy_pass http://$keycloak_server:$keycloak_port;
        proxy_set_header Host               $host;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  $scheme;
        proxy_set_header X-Forwarded-Scheme $scheme;
        proxy_set_header X-Forwarded-Port   $server_port;
        proxy_set_header X-Forwarded-Host   $host;

        proxy_buffer_size                   128k;
        proxy_buffers                       4 256k;
        proxy_busy_buffers_size             256k;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/keycloak.yourdomain/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/keycloak.yourdomain/privkey.pem;
    ssl_session_cache shared:le_nginx_SSL:10m;
    ssl_session_timeout 1440m;
    ssl_session_tickets off;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    ssl_ciphers "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384";
}

server {
    server_name keycloak.yourdomain;  # замените на ваш домен для Keycloak
    listen 80;
    
    if ($host = keycloak.yourdomain) {
        return 301 https://$host$request_uri;
    }
    
    return 404;
}