server {
    set $apphost 192.X.X.X;  # замените на свой IP для unicarch
    set $webui_port 8000;
    set $backend_port 8080;

    server_name unicarch.youdomain;  # замените на ваш домен

    client_max_body_size 200M;

    error_log /var/log/nginx/unicarch.youdomain.error.log;
    access_log /var/log/nginx/unicarch.youdomain.access.log;

    location / {
        proxy_pass http://$apphost:$webui_port;
        proxy_http_version 1.1;
        proxy_set_header Upgrade               $http_upgrade;
        proxy_set_header Connection            "upgrade";
        proxy_set_header Host                  $host;
        proxy_set_header X-Real-IP             $remote_addr;
        proxy_set_header X-Forwarded-For       $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto     https;
        proxy_set_header X-Nginx-Proxy         true;
    }

    location /api/ {
        proxy_pass http://$apphost:$backend_port;
        proxy_set_header Host                  $host;
        proxy_set_header X-Real-IP             $remote_addr;
        proxy_set_header X-Forwarded-For       $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto     $scheme;
        proxy_set_header X-Forwarded-Scheme    $scheme;
        proxy_set_header X-Forwarded-Port      $server_port;
        proxy_set_header X-Forwarded-Host      $host;

        # Отключаем кэш для API
        proxy_cache_bypass 1;
        proxy_no_cache 1;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires "0";
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/unicarch.youdomain/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/unicarch.youdomain/privkey.pem;
    ssl_session_cache shared:le_nginx_SSL:10m;
    ssl_session_timeout 1440m;
    ssl_session_tickets off;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    ssl_ciphers "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384";
}

server {
    server_name unicarch.youdomain;  # замените на ваш домен
    listen 80;

    if ($host = unicarch.youdomain) {
        return 301 https://$host$request_uri;
    }

    return 404;
}
